### ISSUE TITLE
Consolidate and migrate infra to Kubernetes cluster 

### ISSUE THREAD

**Issue by shenanigansd** [vipyrsec/infrastructure#14]
# Summary

Currently our infra is:
- The "old" API running in Azure (The "old" bot is already dead)
- The CronJob running as a Lambda on @Robin5605's AWS account
- The Mainframe running in Azure
- Scattered clients running in different places
- The bot hosted in @shenanigansd's homelab.

We are ready to merge https://github.com/vipyrsec/infrastructure/pull/10 and deploy our entire stack on a single Kubernetes cluster.

# Steps to take before downtime

- [x] Create a new Kubernetes cluster on the team's Digital Ocean account. (Do this first so it has time to spin up)
- [x] Delete my dev cluster
- [x] Delete the "old" API [Azure]
- [x] Delete the `dragonfly.mantissecurity.org` DNS records [Cloudflare]
- [x] Delete the `dragonfly-staging.vipyrsec.com` DNS records [Cloudflare]
- [x] Delete the Sentry projects for the "old" bot and API [Sentry]

# Steps to take during downtime

- [x] Apply pending update to managed DB [Digital Ocean]
- [x] Apply the org Helm Chart to the new cluster (https://github.com/vipyrsec/infrastructure/pull/10)
- [x] Apply the manifests to the new cluster (https://github.com/vipyrsec/infrastructure/pull/10)
- [x] Wait for the ingress to receive it's IP
- [x] Update the DNS records for `dragonfly.vipyrsec.com` with the new IP [Cloudflare]

# Steps to take after downtime

- [x] Create user accounts on the Kubernetes cluster for the core team
- [x] @shenanigansd to schedule time to finalize branding and update the email domain from `mantissecurity.com` to `vipyrsec.com` and let PyPI know about the change.

**Comment by Robin5605** [comment]
@shenanigansd following up on steps to take after downtime, have we switched to `vipyrsec.com` as our email domain, and have we let PyPI know about this change yet?

**Comment by shenanigansd** [comment]
> @shenanigansd following up on steps to take after downtime, have we switched to `vipyrsec.com` as our email domain, and have we let PyPI know about this change yet?

Email domain was handled just now in https://github.com/vipyrsec/dragonfly-mainframe/pull/188

**Comment by shenanigansd** [comment]
User creation is being handled asynchronously 
The scripts used will be added in https://github.com/vipyrsec/infrastructure/pull/39
