### ISSUE TITLE
Colocate DB with API 

### ISSUE THREAD

**Issue by import-pandas-as-numpy** [vipyrsec/infrastructure#26]
Currently we're getting a number of slow DB query notifications on Sentry. I believe this will be slightly alleviated by moving the database closer to the Kubernetes cluster, or vice versa.

**Comment by shenanigansd** [comment]
Currently in progress.
The dashboard says that the database will remain available during the migration, so I went ahead and :shipit:ed it.

**Comment by shenanigansd** [comment]
This is now complete.
