### ISSUE TITLE
`azure/k8s-lint` can't find the metadata schema to validate against

### ISSUE THREAD

**Issue by shenanigansd** [vipyrsec/infrastructure#29]
# Summary

The `azure/k8s-lint` action is currently failing with `ERR  - kubernetes/manifests/cert-manager/cluster_issuer.yaml: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/clusterissuer-cert-manager-v1.json: Could not read schema from HTTP, response status is 404 Not Found`.

# Hypothesis

_Absolutely no idea_
I don't understand how this works yet.

**Comment by Robin5605** [comment]
The `azure/k8s-lint` repository had a commit https://github.com/Azure/k8s-lint/commit/3b7cb68584cd614174f4e2dad0b6d48dbf651ccc migrating away from kubeval on July 25th, while the release we're on (v2.0) is from February 3rd. 
This error might have to do with kubeval being deprecated in favour of kubeconform.

**Comment by shenanigansd** [comment]
Was this solved by #37 ?

**Comment by sid-maddy** [comment]
> Was this solved by #37 ?

Yep.
