### ISSUE TITLE
Rename databases in DO to more easily distinguish prod vs staging

### ISSUE THREAD

**Issue by jonathan-d-zhang** [vipyrsec/infrastructure#48]

**Comment by sid-maddy** [comment]
DigitalOcean doesn't (yet) support renaming databases.
See [this community forum answer](https://www.digitalocean.com/community/questions/how-to-change-name-of-database-cluster?comment=198117) and [this idea (feature request)](https://ideas.digitalocean.com/managed-database/p/allow-renaming-managed-databases).

**Comment by sid-maddy** [comment]
…but this is already solved using tags.
![Database tags](https://github.com/user-attachments/assets/172b318d-b224-4514-a086-6368ed05e8bb)

Closing this issue.
